# Generated by Django 4.2.10 on 2024-04-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0051_alter_consignee_zip_code_alter_customer_zip_code_and_more'),
        ('inventoryapp', '0051_product_product_low_stock_threshold'),
    ]

    operations = [
    ]
