# Generated by Django 5.0.1 on 2024-01-30 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=32)),
                ('Description', models.TextField(max_length=1024)),
                ('low_stock_threshold', models.SmallIntegerField()),
                ('Notes', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EAS_Product_ID', models.CharField(max_length=32, unique=True)),
                ('Name', models.CharField(max_length=64)),
                ('Picture', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=32)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Actual_Inventory_Count', models.SmallIntegerField(default=0)),
                ('Reserved_Inventory_Count', models.SmallIntegerField(default=0)),
                ('To_Be_Received_Inventory_Count', models.SmallIntegerField(default=0)),
                ('Visibility', models.BooleanField(default=True)),
                ('Consignee', models.CharField(max_length=4)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.category')),
            ],
        ),
    ]
