# Generated by Django 5.0.1 on 2024-02-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_alter_product_actual_inventory_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Consignee',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
