# Generated by Django 5.0.1 on 2024-02-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_alter_product_category_alter_product_consignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Reserved_Inventory_Count',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='To_Be_Received_Inventory_Count',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
