# Generated by Django 5.0.1 on 2024-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_alter_product_reserved_inventory_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=32)),
                ('First_name', models.CharField(max_length=32)),
                ('Last_name', models.CharField(max_length=32)),
            ],
        ),
    ]
