# Generated by Django 5.0.1 on 2024-02-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
