# Generated by Django 5.0.1 on 2024-02-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Account_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=32)),
                ('First_name', models.CharField(max_length=32)),
            ],
        ),
    ]
