# Generated by Django 5.0.1 on 2024-02-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_count_edit_history_product_requisition_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Low_Stock_Threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
