# Generated by Django 5.0.1 on 2024-02-07 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0009_alter_product_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Actual_Inventory_Count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Low_Stock_Threshold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Reserved_Inventory_Count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='To_Be_Received_Inventory_Count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
