# Generated by Django 5.0.1 on 2024-02-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_alter_product_actual_inventory_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Count_Edit_History',
        ),
        migrations.RemoveField(
            model_name='partially_fulfilled_history',
            name='Account_ID',
        ),
        migrations.RemoveField(
            model_name='partially_fulfilled_history',
            name='Product_ID',
        ),
        migrations.RemoveField(
            model_name='partially_fulfilled_history',
            name='Product_Requisition_ID',
        ),
        migrations.DeleteModel(
            name='Purchase_Order',
        ),
        migrations.AddField(
            model_name='account',
            name='Last_name',
            field=models.CharField(default='Testerson', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='account',
            name='Role',
            field=models.CharField(default='Employee', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Partially_Fulfilled_History',
        ),
        migrations.DeleteModel(
            name='Product_Requisition_Order',
        ),
    ]
