# Generated by Django 5.0.1 on 2024-02-08 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0014_alter_category_category_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Product_Low_Stock_Threshold',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='Zip_Code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='count_edit_history',
            name='Initial_Inventory_Count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='count_edit_history',
            name='Updated_Inventory_Count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Zip_Code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='partially_fulfilled_history',
            name='Partially_Fulfilled_Quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Actual_Inventory_Count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Low_Stock_Threshold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Reserved_Inventory_Count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='To_Be_Received_Inventory_Count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='products_ordered',
            name='Quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='stocks_ordered',
            name='Quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
