# Generated by Django 5.0.1 on 2024-02-08 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0015_alter_category_category_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Consignee',
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.category'),
        ),
    ]
