# Generated by Django 5.0.1 on 2024-02-13 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0018_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee_product',
            name='Consignee_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.consignee'),
        ),
        migrations.AlterField(
            model_name='consignee_product',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.product'),
        ),
        migrations.AlterField(
            model_name='count_edit_history',
            name='Account_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
        ),
        migrations.AlterField(
            model_name='count_edit_history',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.product'),
        ),
        migrations.AlterField(
            model_name='partially_fulfilled_history',
            name='Account_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
        ),
        migrations.AlterField(
            model_name='partially_fulfilled_history',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.product'),
        ),
        migrations.AlterField(
            model_name='partially_fulfilled_history',
            name='Product_Requisition_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.product_requisition_order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.category'),
        ),
        migrations.AlterField(
            model_name='product_requisition_order',
            name='Account_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
        ),
        migrations.AlterField(
            model_name='products_ordered',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.product'),
        ),
        migrations.AlterField(
            model_name='products_ordered',
            name='Purchase_Order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.purchase_order'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='Account_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='Consignee_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.consignee'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='Customer_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.customer'),
        ),
        migrations.AlterField(
            model_name='stocks_ordered',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.product'),
        ),
        migrations.AlterField(
            model_name='stocks_ordered',
            name='Product_Requisition_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.product_requisition_order'),
        ),
    ]
