# Generated by Django 5.0.2 on 2024-03-03 10:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0019_alter_consignee_product_consignee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_ordered',
            name='Total',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.category'),
        ),
    ]
