# Generated by Django 5.0.2 on 2024-03-03 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0020_products_ordered_total_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_ordered',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
