# Generated by Django 5.0.2 on 2024-03-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0021_alter_products_ordered_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Stock_Status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
