# Generated by Django 5.0.2 on 2024-03-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0022_alter_product_product_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_ordered',
            name='Total',
        ),
    ]
