# Generated by Django 5.0.2 on 2024-03-11 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0023_remove_products_ordered_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='Account_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
        ),
    ]
