# Generated by Django 5.0.2 on 2024-03-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0024_alter_purchase_order_account_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Ordered',
            new_name='Product_Ordered',
        ),
        migrations.RenameModel(
            old_name='Stocks_Ordered',
            new_name='Stock_Ordered',
        ),
    ]
