# Generated by Django 5.0.2 on 2024-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0026_alter_purchase_order_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_edit_history',
            name='Date_Updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partially_fulfilled_history',
            name='Date_Updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product_requisition_order',
            name='Creation_Date',
            field=models.DateTimeField(),
        ),
    ]
