# Generated by Django 5.0.2 on 2024-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0027_alter_count_edit_history_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignee',
            old_name='Customer_Name',
            new_name='Consignee_Name',
        ),
        migrations.AddField(
            model_name='consignee',
            name='Consignee_Name',
            field=models.CharField(default='consignee', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consignee',
            name='Consignee_Tag_ID',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
