# Generated by Django 5.0.2 on 2024-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0027_alter_count_edit_history_date_updated_and_more'),
    ]

    operations = [
    ]
