# Generated by Django 5.0.2 on 2024-03-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0028_remove_consignee_customer_name_and_more'),
    ]

    operations = [
    ]
