# Generated by Django 5.0.2 on 2024-03-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0029_alter_consignee_consignee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_requisition_order',
            name='Account_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
        ),
    ]
