# Generated by Django 5.0.2 on 2024-03-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0032_remove_account_password_remove_account_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Stock_Status',
            field=models.CharField(default='Regular Stock', max_length=16),
            preserve_default=False,
        ),
    ]
