# Generated by Django 5.0.2 on 2024-04-16 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0035_remove_purchase_order_account_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count_edit_history',
            name='Account_ID',
        ),
        migrations.RemoveField(
            model_name='partially_fulfilled_history',
            name='Account_ID',
        ),
        migrations.RemoveField(
            model_name='product_requisition_order',
            name='Account_ID',
        ),
        migrations.AddField(
            model_name='count_edit_history',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partially_fulfilled_history',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product_requisition_order',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
