# Generated by Django 5.0.2 on 2024-04-16 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0036_remove_count_edit_history_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count_edit_history',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='partially_fulfilled_history',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='product_requisition_order',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='User_ID',
        ),
        migrations.AddField(
            model_name='count_edit_history',
            name='Account_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partially_fulfilled_history',
            name='Account_ID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_requisition_order',
            name='Account_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='Account_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.account'),
        ),
    ]
