# Generated by Django 5.0.2 on 2024-04-16 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0037_remove_count_edit_history_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_requisition_order',
            name='Account_ID',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='Account_ID',
        ),
        migrations.AddField(
            model_name='product_requisition_order',
            name='Account_ID_Closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_closed', to='inventoryapp.account'),
        ),
        migrations.AddField(
            model_name='product_requisition_order',
            name='Account_ID_Created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_created', to='inventoryapp.account'),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='Account_ID_Closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_closed', to='inventoryapp.account'),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='Account_ID_Created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_created', to='inventoryapp.account'),
        ),
    ]
