# Generated by Django 4.2.10 on 2024-04-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0038_remove_product_requisition_order_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Hex_Color_ID',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='Tag_Hex_Color_ID',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
