# Generated by Django 5.0.2 on 2024-04-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0040_remove_consignee_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignee',
            name='Customer_Name',
        ),
        migrations.AddField(
            model_name='consignee',
            name='Consignee_Name',
            field=models.CharField(default='con', max_length=32),
            preserve_default=False,
        ),
    ]
