# Generated by Django 5.0.2 on 2024-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0041_remove_consignee_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='Consignee_Name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
