# Generated by Django 5.0.2 on 2024-04-29 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0043_account_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Visibility',
        ),
        migrations.AlterField(
            model_name='category',
            name='Category_Product_Low_Stock_Threshold',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='count_edit_history',
            name='Initial_Inventory_Count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='count_edit_history',
            name='Updated_Inventory_Count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='partially_fulfilled_history',
            name='Partially_Fulfilled_Quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Actual_Inventory_Count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Low_Stock_Threshold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Reserved_Inventory_Count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='To_Be_Received_Inventory_Count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='product_ordered',
            name='Quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='stock_ordered',
            name='Quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
