# Generated by Django 5.0.2 on 2024-04-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0044_remove_account_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Visibility',
            field=models.BooleanField(default=True),
        ),
    ]
