# Generated by Django 5.0.2 on 2024-04-29 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0045_account_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Low_Stock_Threshold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
