# Generated by Django 5.0.2 on 2024-04-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0047_product_product_low_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partially_fulfilled_history',
            name='Product_ID',
        ),
        migrations.RemoveField(
            model_name='partially_fulfilled_history',
            name='Product_Requisition_ID',
        ),
        migrations.AddField(
            model_name='partially_fulfilled_history',
            name='Stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.stock_ordered'),
            preserve_default=False,
        ),
    ]
