# Generated by Django 5.0.2 on 2024-04-29 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0048_remove_partially_fulfilled_history_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_requisition_order',
            name='Account_ID_Created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='pro_created', to='inventoryapp.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='Account_ID_Created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='po_created', to='inventoryapp.account'),
            preserve_default=False,
        ),
    ]
