# Generated by Django 5.0.2 on 2024-04-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0049_alter_product_requisition_order_account_id_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Last_name',
        ),
    ]
