# Generated by Django 4.2.10 on 2024-04-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0049_alter_product_requisition_order_account_id_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Low_Stock_Threshold',
        ),
    ]
