# Generated by Django 5.0.2 on 2024-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0051_alter_consignee_zip_code_alter_customer_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='First_Name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='Last_Name',
            field=models.CharField(default='Smith', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='Category_Name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
