# Generated by Django 5.0.2 on 2024-05-05 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0052_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='Emergency_Contact_Number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='count_edit_history',
            name='Text_Report',
            field=models.TextField(default='report', validators=[django.core.validators.MaxLengthValidator(1024)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partially_fulfilled_history',
            name='Text_Report',
            field=models.TextField(default='report', validators=[django.core.validators.MaxLengthValidator(1024)]),
            preserve_default=False,
        ),
    ]
